//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPandit.Repository.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanditDetail
    {
        public int PanditDetailId { get; set; }
        public long UserMasterId { get; set; }
        public Nullable<double> YearsOfExperience { get; set; }
        public string PanditDescription { get; set; }
        public string OrganisationName { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
