//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPandit.Repository.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public long UserMasterId { get; set; }
        public int UserRoleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LoginId { get; set; }
        public long MobileNumber { get; set; }
        public Nullable<long> WhatsappMobileNumber { get; set; }
        public Nullable<long> AlternateMobileNumber1 { get; set; }
        public Nullable<long> AlternateMobileNumber2 { get; set; }
        public Nullable<long> AlternateMobileNumber3 { get; set; }
        public string UserAddress { get; set; }
        public string HomeLongitude { get; set; }
        public string HomeLatitude { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string UserPassword { get; set; }
        public string UserImage { get; set; }
        public string UserCity { get; set; }
        public string UserState { get; set; }
        public int PinCode { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual UserRole UserRole { get; set; }
    }
}
